### ISSUE TITLE
permission denied error

### ISSUE THREAD

**Issue by YingHu-jlau** [oushujun/LTR_FINDER_parallel#3]
Dear Shujun,

Thanks for developing this perl script to run ltr_finder. I tried to use it but always get permission denied error.

I downloaded and saved everything to our university sever. Here is my script:
perl /script/ltrfinder_parallel/LTR_FINDER_parallel -seq test.fa -threads 36 -harvest_out

Here is the error message:
Thu Aug  1 16:35:40 2019 CPU1: running on Chr1_sub1
Thu Aug  1 16:35:40 2019 CPU2: running on Chr1_sub2
Thu Aug  1 16:35:40 2019 CPU3: running on Chr1_sub3
Thu Aug  1 16:35:40 2019 CPU4: running on Chr1_sub4
Thu Aug  1 16:35:40 2019 CPU5: running on Chr1_sub5
Thu Aug  1 16:35:40 2019 CPU6: running on Chr1_sub6
Thu Aug  1 16:35:40 2019 CPU7: running on Chr1_sub7
Thu Aug  1 16:35:40 2019 CPU8: running on Chr1_sub8
Thu Aug  1 16:35:40 2019 CPU9: running on Chr1_sub9
Thu Aug  1 16:35:40 2019 CPU10: running on Chr1_sub10
Thu Aug  1 16:35:40 2019 CPU11: running on Chr1_sub11
Thu Aug  1 16:35:40 2019 CPU12: running on Chr1_sub12
Thu Aug  1 16:35:40 2019 CPU13: running on Chr1_sub13
Thu Aug  1 16:35:40 2019 CPU14: running on Chr1_sub14
Thu Aug  1 16:35:40 2019 CPU15: running on Chr1_sub15
Thu Aug  1 16:35:40 2019 CPU16: running on Chr1_sub16
Thu Aug  1 16:35:40 2019 CPU17: running on Chr1_sub17
Thu Aug  1 16:35:40 2019 CPU18: running on Chr1_sub18
Thu Aug  1 16:35:40 2019 CPU19: running on Chr1_sub19
Thu Aug  1 16:35:40 2019 CPU20: running on Chr1_sub20
Thu Aug  1 16:35:40 2019 CPU21: running on Chr1_sub21
Thu Aug  1 16:35:40 2019 CPU22: running on Chr1_sub22
Thu Aug  1 16:35:40 2019 CPU23: running on Chr1_sub23
Thu Aug  1 16:35:40 2019 CPU24: running on Chr1_sub24
Thu Aug  1 16:35:40 2019 CPU25: running on Chr1_sub25
timeout: failed to run command ‘/script/ltrfinder_parallel/bin/LTR_FINDER.x86_64-1.0.7/ltr_finder’: Permission denied
Thu Aug  1 16:35:40 2019 CPU6: Chr1_sub6 timeout, process it with the salvage mode
timeout: failed to run command ‘/script/ltrfinder_parallel/bin/LTR_FINDER.x86_64-1.0.7/ltr_finder’: Permission denied
Thu Aug  1 16:35:41 2019 CPU10: Chr1_sub10 timeout, process it with the salvage mode

I am curious why some sub-sequences are successfully processed but some are not. Thanks for your help!

Ying

**Comment by oushujun** [comment]
Hi Ying,

Thanks for the report. I don't know. I never saw this kind of error on LTR_FINDER_parallel before. To make sure, you may want to check if `/script/ltrfinder_parallel/bin/LTR_FINDER.x86_64-1.0.7/ltr_finder` is executable. If not, simply do `chmod +x /script/ltrfinder_parallel/bin/LTR_FINDER.x86_64-1.0.7/ltr_finder` will fix it. But since other threads were working OK, so I don't know what was the real cause. Did you see this persistently? Maybe you can also reduce the thread number.

Shujun

**Comment by YingHu-jlau** [comment]
Hi, Shujun,

Thanks for your reply! 

I changed CPU cores per task from 36 to 4 in my SLURM submission scripts and still keep threads in the script as 36. Now it works. 

Here is my script:
#!/bin/bash
#SBATCH --job-name=parallel_ltrretriever # Job name
#SBATCH --mail-type=ALL              # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=  # Where to send mail     
#SBATCH --nodes=1                    # Use one node
#SBATCH --ntasks=1                   # Run a single task        
#SBATCH --cpus-per-task=4            # Number of CPU cores per task
#SBATCH --mem=8gb                    # Total memory limit
#SBATCH --time=96:00:00              # Time limit hrs:min:sec
#SBATCH --output=parallel_%j.out     # Standard output and error logI


perl /script/ltrfinder_parallel/LTR_FINDER_parallel -seq test.fa -threads 36 -harvest_out

**Comment by oushujun** [comment]
Hi Ying,

You should apply for more or equal CPUs than you use in the program. eg.,
`#SBATCH --cpus-per-task=36`
`perl /script/ltrfinder_parallel/LTR_FINDER_parallel -seq test.fa -threads 35 -harvest_out`

Otherwise you are providing the program fewer CPUs than you are telling it to use. If your HPC admin enforces CPU usage check, it may cause your job being killed due to overutilization of resources.

Hope it helps!

Shujun
